name: Sync notes repos

on:
  repository_dispatch:
    types: [update]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: SSH configuration
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.GH_ACTIONS_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
      - name: Clone external repo
        run: git clone ${{ secrets.NOTES_REPO }} notes-repo
      - name: Clone this repo
        uses: actions/checkout@v3
        with:
          path: this-repo
      - name: Sync
        run: |
          cd this-repo
          rsync -r ../notes-repo/public/* ./notes
          ls notes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add notes
          git commit -m "Sync update: `date`"
          git push
  deploy:
    name: Deploy to GitHub Pages
    depends-on: [sync]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
