on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: SSH configuration
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.GH_ACTIONS_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
      - name: Clone external repo
        run: git clone ${{ secrets.NOTES_REPO }} notes-repo
      - name: Clone this repo
        uses: actions/checkout@v3
        with:
          path: this-repo
      - name: Sync
        run: |
          cd this-repo
          rsync -r ../notes-repo/public/* ./notes
          ls notes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add notes
          git commit -m "`date`"
          git push
