on: [workflow_dispatch]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH private key
        run: mkdir ~/.ssh > echo "{{ secrets.GH_ACTIONS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      - name: Clone external repo
        run: git clone {{ secrets.NOTES_REPO }} /notes-repo
      - name: Clone this repo
        uses: actions/checkout@v3
      - name: Sync
        run: |
          rsync -r /notes-repo/public/* ./notes
          ls notes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add notes
          git commit -m "generated"
          # git push
